from functions.week4.language_detection import tweets
from functions.week4.sentiment_detection import draw_mandel
from functions.week2.pagerank_algorithm import barabasi_albert_network, squirrel_edges
